[auth]
allowed_redirect_urls = [
  "http://localhost:3000/login",
  "http://localhost:3000/reset-password",
  "https://spendly.syedfatikislam.com/login",
  "https://spendly.syedfatikislam.com/reset-password",
]
